<?php

namespace App\Modules\Design;

use App\Core\Blocks;
use App\Modules\Design\Vocabulary\Decisions;
use App\Modules\Design\Vocabulary\Descriptions;
use App\Modules\Pages\SectionLayout;

/**
 * THE DESIGN SET REFERENCE (PLAN.md D-183): every key a set may hold, with its type, range,
 * step, default and what it does; the surfaces, blocks, layouts and options; the contrast rules
 * an import holds a set to; and how patterns carry words. Markdown, for the person who writes
 * sets by hand.
 *
 * Written from the same tables the validator reads (DesignVocabulary, Decisions, SectionStyle,
 * the block registry, PalettePairs), as the schema is, so it cannot describe a key the
 * validator does not take. `php bin/design-reference.php` prints it.
 */
final class DesignReference
{
    public static function markdown(Blocks $registry): string
    {
        $vocabulary = DesignVocabulary::vocabulary($registry);
        $out = [];
        $out[] = '# Boxlet design set reference (format v' . DesignSet::VERSION . ')';
        $out[] = '';
        $out[] = 'Generated by `php bin/design-reference.php` from the code that validates a set; the JSON Schema is `designs/design-set.schema.json`, from the same code. Check a file with `php bin/check-set.php file.json`.';
        $out[] = '';
        $out[] = '**Frozen.** Version ' . DesignSet::VERSION . ' changes only by adding optional keys that have a default, so every v' . DesignSet::VERSION . ' file stays valid. Anything else — a key removed, renamed or made required, a value taken away, a meaning changed — is version ' . (DesignSet::VERSION + 1) . '. A key Boxlet does not know is left out with a warning, never refused, so a file written for a later v' . DesignSet::VERSION . ' still imports into an earlier Boxlet.';
        $out[] = '';
        $out[] = '## The file';
        $out[] = '';
        $out[] = '| Key | Required | What it is |';
        $out[] = '|---|---|---|';
        $out[] = '| `format` | yes | Always `"' . DesignSet::FORMAT . '"`. |';
        $out[] = '| `version` | yes | Always `' . DesignSet::VERSION . '`. |';
        $out[] = '| `id` | yes | Lower-case letters, digits and hyphens, up to 32, starting with a letter or digit. An id Boxlet already has is imported as `id-2`. |';
        $out[] = '| `name` | yes | Per language, `{"en": "…", "hr": "…"}`, up to 80 characters each. |';
        $out[] = '| `description` | no | Per language, up to 300 characters each. |';
        $out[] = '| `author` | no | Up to 80 characters. |';
        $out[] = '| `tags` | no | Up to 12 words, each up to 32 characters. |';
        $out[] = '| `decisions` | yes | The design: colour, type, space, layout, buttons. Only `seed` is required; a key left out takes its default. |';
        $out[] = '| `look` | no | The header and footer. A key left out, or `""`, follows the character. |';
        $out[] = '| `composition` | no | What each section and block looks like by default. With it the set is a character. |';
        $out[] = '| `patterns` | no | Up to ' . DesignSetPatterns::MAX . ' starter sections, the one place a set carries words. |';
        $out[] = '';
        $out[] = 'A number may be written as a number or a string (`60` or `"60"`); it must lie in its range, and one off its step is put on the nearest step (`bin/check-set.php` says so). A colour is `#rgb` or `#rrggbb`. `""` means *follow*: the character\'s value, the typeface pairing\'s, or the palette\'s (column **""**).';
        $out[] = '';

        foreach (['decisions' => 'Decisions', 'look' => 'Look: the header and footer'] as $part => $title) {
            $out[] = '## ' . $title;
            $out[] = '';
            $out[] = '| Key | Type | Values | Step | Default | "" | What it does |';
            $out[] = '|---|---|---|---|---|---|---|';
            foreach (Decisions::ALL as $key => $rule) {
                if ($rule['part'] !== $part) {
                    continue;
                }
                $out[] = '| `' . $key . '` | ' . $rule['type'] . (isset($rule['unit']) ? ' (' . $rule['unit'] . ')' : '')
                    . ' | ' . self::values($rule)
                    . ' | ' . (isset($rule['step']) ? self::number($rule['step']) : '')
                    . ' | ' . ($rule['neutral'] === '' ? '""' : '`' . $rule['neutral'] . '`')
                    . ' | ' . (isset($rule['follow']) ? $rule['follow'] : ($rule['type'] === 'colour' && $key !== 'seed' ? 'no colour' : ''))
                    . ' | ' . Descriptions::KEYS[$key] . ' |';
            }
            $out[] = '';
        }

        $out[] = '## Composition';
        $out[] = '';
        $out[] = '`composition.section` is every new section\'s style; `surfaces` and `dividers` give a block type its own (`{"hero": "contrast"}`); `layouts` a block type\'s layout; `options` a block type\'s options. A block type or layout this site does not have is left out with a warning.';
        $out[] = '';
        $out[] = '| Section key | Values | Default | What it does |';
        $out[] = '|---|---|---|---|';
        foreach ($vocabulary['composition']['section'] as $key => $values) {
            $default = SectionStyle::DEFAULTS[$key] ?? '';
            $out[] = '| `' . $key . '` | ' . (isset($values['step'])
                    ? self::number($values['min']) . ' – ' . self::number($values['max']) . ', step ' . self::number($values['step'])
                    : implode(', ', array_map(static fn (string $v): string => '`' . $v . '`', $values)))
                . ' | ' . ($default === '' ? '""' : '`' . $default . '`')
                . ' | ' . (Descriptions::SECTION[$key] ?? '') . ' |';
        }
        $out[] = '';
        $out[] = '**Surfaces** a composition may give: ' . implode(', ', array_map(static fn (string $v): string => '`' . $v . '`', $vocabulary['composition']['surfaces'])) . '. `image` is a section with a picture, which only a page has.';
        $out[] = '';
        $out[] = '**Section column layouts** (a pattern\'s `section.layout`): ' . implode(', ', array_map(static fn (string $l, array $w): string => '`' . $l . '` (' . implode(':', $w) . ')', array_keys(SectionLayout::LAYOUTS), SectionLayout::LAYOUTS)) . '.';
        $out[] = '';

        $out[] = '## Blocks, layouts and options';
        $out[] = '';
        $out[] = '| Block | Layouts (first is the default) | Options |';
        $out[] = '|---|---|---|';
        foreach ($registry->types() as $type) {
            $options = [];
            foreach ($registry->get($type)['options'] as $name => $spec) {
                $options[] = '`' . $name . '`: ' . ($spec['type'] === 'choice'
                    ? implode(', ', $spec['values'])
                    : self::number($spec['min']) . ' – ' . self::number($spec['max']) . ', step ' . self::number($spec['step'])) . ' (default ' . $spec['default'] . ')';
            }
            $out[] = '| `' . $type . '` | ' . implode(', ', $registry->get($type)['layouts']) . ' | ' . implode('; ', $options) . ' |';
        }
        $out[] = '';

        $out[] = '## Contrast: what an import checks';
        $out[] = '';
        $out[] = 'Every pair below must read at ' . Palette::AA_BODY . ':1 (WCAG AA for body text) in the set\'s own `mode`, or the set is refused, naming the pair and the key responsible. `bin/check-set.php` also measures the other mode and warns, since an owner may switch it.';
        $out[] = '';
        foreach (self::pairNames() as $pair) {
            $out[] = '- ' . t('design.pair.' . $pair) . ' (`' . $pair . '`)';
        }
        $out[] = '';
        $out[] = 'What is worked out rather than set, so that it passes:';
        $out[] = '';
        $out[] = '- The ink on the main colour, on the contrast colour and on the gradient is whichever of the page\'s two inks reads better there.';
        $out[] = '- Each surface\'s muted ink is derived to read on that surface **and on a card raised from it**: a contrast band\'s muted words on its cards, a header\'s or footer\'s own colour likewise.';
        $out[] = '- Over a picture (a section\'s or a cover hero\'s), the words are the contrast surface\'s ink on a veil of the contrast colour, never weaker than what keeps them at ' . Palette::AA_BODY . ':1 over a pure white and a pure black picture.';
        $out[] = '';
        $out[] = 'Colours set by hand (`color_*`, `header_colour`, `footer_colour`) are measured like the rest; a failure names that key.';
        $out[] = '';

        $out[] = '## Patterns';
        $out[] = '';
        $out[] = 'A pattern is `{"id", "name", "section": {"layout", "style"}, "blocks": [...]}`: up to ' . DesignSetPatterns::MAX . ' patterns, up to four blocks each, each block `{"type", "layout", "column", "options", "content"}`. `column` counts from 0 in the section\'s layout.';
        $out[] = '';
        $out[] = '- **Words are per language**: `{"en": "Get in touch", "hr": "Javite se"}`, or one string, which is kept as English. A page in a language the pattern has no words for takes the English.';
        $out[] = '- A line or a paragraph (`text`, `textarea`) is plain text up to 500 characters; rich text up to 4000, through the same sanitiser as the editor, keeping only what the field allows.';
        $out[] = '- A link is `{"label": {"en": "…"}, "url": "/contact"}`: an address any link field takes (a path, https, mailto, tel).';
        $out[] = '- A choice field takes one of its values; a repeater a list of items, each written the same way.';
        $out[] = '- **No pictures, files or forms**: a set carries no media. Such a field is left out with a warning.';
        $out[] = '';
        $out[] = 'A block\'s fields:';
        $out[] = '';
        foreach ($registry->types() as $type) {
            $out[] = '- `' . $type . '`: ' . self::fields($registry->get($type)['fields']);
        }
        $out[] = '';

        $out[] = '## Errors and warnings';
        $out[] = '';
        $out[] = '- **An error refuses the set**: not JSON, not this format or version, no `id` or `name`, a number out of its range, a choice not in its list, a contrast pair under ' . Palette::AA_BODY . ':1, a pattern without blocks.';
        $out[] = '- **A warning keeps the set** and says what was left out: a key Boxlet does not know, a block type, layout, option or field this site does not have, a picture, file or form in a pattern.';
        $out[] = '- `bin/check-set.php` warns besides about a text column under 16rem on a large screen, a number put on its step, and the other mode\'s contrast.';

        return implode("\n", $out) . "\n";
    }

    /**
     * Every pair the check measures, including those only a header's or footer's own colour has.
     *
     * @return list<string>
     */
    public static function pairNames(): array
    {
        $colors = Palette::colors('#3a4250', '', 20.0);

        return array_column(PalettePairs::pairs($colors, false, [], ['header' => '#202020', 'footer' => '#202020']), 'pair');
    }

    /** @param array<string, mixed> $rule */
    private static function values(array $rule): string
    {
        return match ($rule['type']) {
            'number' => self::number($rule['min']) . ' – ' . self::number($rule['max']),
            'choice' => implode(', ', array_map(static fn (string $v): string => '`' . $v . '`', $rule['values'])),
            'colour' => '#rgb, #rrggbb',
            default => '',
        };
    }

    /** @param array<string, array<string, mixed>> $fields */
    private static function fields(array $fields): string
    {
        $out = [];
        foreach ($fields as $name => $field) {
            $kind = match ($field['type']) {
                'repeater' => 'items of {' . self::fields($field['fields']) . '}',
                'select' => 'one of ' . implode(', ', $field['options']),
                'richtext' => 'rich text (' . implode(', ', $field['allow'] ?? ['bold', 'italic', 'link', 'heading', 'list', 'quote']) . ')',
                'media', 'file', 'form' => $field['type'] . ', not in a set',
                default => $field['type'],
            };
            $out[] = '`' . $name . '` ' . $kind;
        }

        return implode(', ', $out);
    }

    private static function number(mixed $value): string
    {
        return CssNumber::of((float) $value);
    }
}
