<?php

/*
 * THE REJECTION RULES. Each returns why a candidate is refused, or null. A rule that reads
 * words (a title, tags, a description) can only guess, so the uncertain ones FLAG a picture
 * for the owner's look in _review.html rather than refuse it.
 *
 * Which rules apply where:
 *   photographs (space, food, books, workshop, texture): every rule;
 *   art: no rule about faces, text or borders — a printed figure is not a person, a poster
 *        is its words, a print's paper margin is the print (margins are trimmed instead) —
 *        but a collage, an overlay or a watermark is refused here too;
 *   archive: faces are flagged, not refused — a print shop of 1900 is its workers.
 */

const PHOTO_REFUSED = [
    'logo', 'logos', 'brand', 'branding', 'trademark', 'signage', 'billboard', 'neon sign', 'shop sign', 'storefront',
    'screen', 'laptop', 'computer', 'monitor', 'smartphone', 'iphone', 'television', 'tablet',
    'mural', 'graffiti', 'painting', 'paintings', 'artwork', 'poster', 'posters', 'sculpture',
    'watermark', 'collage', 'overlay', 'mockup', 'mock-up', 'template', 'text', 'quote', 'lettering', 'typography',
    'portrait', 'selfie', 'model posing',
];

/** Refused in every folder, art and archive too: not a picture of one thing as it is. */
const ALWAYS_REFUSED = ['collage', 'overlay', 'watermark', 'watermarked', 'mockup', 'mock-up', 'template'];

/**
 * Pixabay: a photograph its uploader did not take, or not a photograph — the owner's rule for
 * a photo search (D-209). Tags are all Pixabay gives; its own AI and low-quality marks come as
 * fields and are read first.
 */
const PIXABAY_REFUSED = [
    'ai', 'ai generated', 'ai-generated', 'generated', 'artificial intelligence', 'midjourney', 'stable diffusion',
    'illustration', 'digital art', 'digital', '3d', 'render', 'rendering', 'vector', 'clipart', 'cartoon',
    'drawing', 'graphic', 'composite', 'manipulation', 'photoshop', 'fantasy', 'concept art', 'editorial',
    // Desktop art, not a photograph: "vehicle car wallpapers" was a composite.
    'wallpaper', 'wallpapers',
];

const PEOPLE_WORDS = ['person', 'people', 'man', 'woman', 'men', 'women', 'girl', 'boy', 'child', 'kid', 'couple', 'crowd', 'face', 'smiling', 'friends', 'family'];

const UPLOADER_REFUSED = [
    ' inc', 'inc.', 'ltd', 'llc', 'gmbh', 'corp', 'company', 'magazine', 'agency', 'media', 'news',
    'wallpaper', 'free images', 'freeimages', 'free stock', 'stock photo', 'stockphoto', 'pixabay', 'unsplash',
    'pexels', 'shutterstock', 'freepik', 'rawpixel',
];

function demo_words(string $text): string
{
    // Screen printing is the craft asked for, not a screen in the frame.
    $text = (string) preg_replace('~\b(silk\s*)?screen[\s-]*print\w*~i', 'printmaking', $text);

    return ' ' . strtolower((string) preg_replace('~[^a-z0-9]+~i', ' ', $text)) . ' ';
}

/** The first of $list that $text holds as words, or null. */
function demo_says(string $text, array $list): ?string
{
    $words = demo_words($text);
    foreach ($list as $word) {
        if (str_contains($words, ' ' . trim(strtolower((string) preg_replace('~[^a-z0-9]+~i', ' ', $word))) . ' ')) {
            return $word;
        }
    }

    return null;
}

/** Why its description alone refuses it, before anything is downloaded. */
function demo_refused(array $c, string $category, int $minSide): ?string
{
    // The Met's search finds a word in an object's tags: a lacquer box answers "woodblock print".
    // Art is a print, a drawing, a painting, a poster or a book; the archive is about printing.
    if ($category === 'art' && isset($c['kind']) && preg_match('~print|drawing|painting|poster|book|illustrat|specimen|ephemera|lithograph|etching|engraving|woodcut|linocut|screenprint|serigraph|watercolou?r|gouache|collotype|lettering~i', (string) $c['kind']) !== 1) {
        return 'not a print, drawing, painting, poster or book (' . trim((string) $c['kind']) . ')';
    }
    // By its title and tags only: The Met's department is "Drawings and Prints" for every print.
    if ($category === 'archive' && preg_match('~print|press|typ|compositor|letterpress~i', (string) ($c['subject'] ?? $c['title'])) !== 1) {
        return 'nothing in its title or tags is about printing';
    }
    // A satire laughs at a group (D-210: The Macaroni Print Shop); the archive shows the trade.
    if ($category === 'archive' && preg_match('~caricature|satir|macaroni~i', (string) ($c['subject'] ?? $c['title'])) === 1) {
        return 'a caricature or satire: it mocks a group';
    }
    $licence = ['Pexels' => 'Pexels License', 'Pixabay' => 'Pixabay Content License'][$c['source']] ?? 'CC0 1.0';
    if ($c['license'] !== $licence) {
        return "licence is not exactly {$licence}: {$c['license']}";
    }
    if ($c['source'] === 'Pixabay') {
        if ($c['ai']) {
            return 'marked as AI-generated by Pixabay';
        }
        if ($c['low_quality']) {
            return 'marked as low quality by Pixabay';
        }
        $said = demo_says($c['text'], PIXABAY_REFUSED);
        if ($said !== null) {
            return "its tags say \"{$said}\": not a photograph its uploader took";
        }
        // Pixabay answers any word of a search, and order=popular puts its most viewed first:
        // "empty exhibition hall" gave a galaxy, "large windows industrial" giraffes. Two of the
        // search's words in the tags, or one where it has no more than two.
        // Not for a picture chosen in review by its id, which came from no search.
        $searched = explode(':', (string) ($c['query'] ?? ''), 2)[1] ?? '';
        $words = $searched === 'chosen' ? [] : array_values(array_diff(preg_split('~\s+~', strtolower(trim($searched))) ?: [], ['on', 'and', 'with', 'of', 'the', 'a']));
        $hits = count(array_filter($words, static fn (string $w): bool => demo_says($c['text'], [$w, rtrim($w, 's'), $w . 's']) !== null));
        if ($words !== [] && $hits < (count($words) <= 2 ? 1 : 2)) {
            return 'off the search "' . implode(' ', $words) . '": its tags hold ' . $hits . ' of its words';
        }
    }
    if (str_starts_with($c['source'], 'Openverse/')) {
        if (trim((string) $c['license_raw']) !== 'cc0 1.0') {
            return 'Openverse licence is not exactly cc0 1.0: ' . $c['license_raw'];
        }
        $who = demo_says($c['creator'] . ' ' . $c['provider'], UPLOADER_REFUSED);
        if ($who !== null) {
            return "uploader is a brand, an aggregator or a free-images account ({$who}: {$c['creator']})";
        }
        $said = demo_says($c['text'], ['via', 'magazine', 'agency', 'wallpaper']);
        if ($said !== null) {
            return "title or tags mention \"{$said}\"";
        }
    }
    $said = demo_says($c['title'], ALWAYS_REFUSED);
    if ($said !== null) {
        return "its title says \"{$said}\"";
    }
    // Pixabay's own floor where its key gives no file larger than 1280 px.
    $minSide = ($c['max_source_px'] ?? 0) > 0 ? (int) $c['max_source_px'] : $minSide;
    if ($c['width'] > 0 && max($c['width'], $c['height']) < $minSide) {
        return "below {$minSide} px on its longer side ({$c['width']}×{$c['height']})";
    }
    if ($category !== 'art' && $category !== 'archive') {
        $said = demo_says($c['text'], PHOTO_REFUSED);
        if ($said !== null) {
            return "its description mentions \"{$said}\" (logo, screen, text, a work of art or a face in the frame)";
        }
    }

    return null;
}

/**
 * What the owner should look at: the rules that words cannot settle.
 *
 * @return list<string>
 */
function demo_flags(array $c, string $category, bool $detector): array
{
    $flags = [];
    if ($category !== 'art' && demo_says($c['text'], PEOPLE_WORDS) !== null) {
        $flags[] = $detector ? 'people in the description: no face found, look anyway' : 'people in the description: check for faces';
    }
    if ($category !== 'art' && $category !== 'archive') {
        $flags[] = 'check for logos, readable signs or text';
    }
    if ($category === 'space') {
        $flags[] = 'check for works of art in the frame';
    }

    return $flags;
}

/**
 * Faces the detector finds in each file, by file; [] for every file when there is no detector.
 *
 * @param list<string> $files
 * @return array<string, list<list<int>>>
 */
function demo_faces(array $files, ?string $python): array
{
    if ($python === null || $files === []) {
        return [];
    }
    $command = escapeshellarg($python) . ' ' . escapeshellarg(__DIR__ . '/faces.py') . ' ' . implode(' ', array_map('escapeshellarg', $files));
    $found = [];
    foreach (explode("\n", (string) shell_exec($command . ' 2>/dev/null')) as $line) {
        $row = json_decode($line, true);
        if (is_array($row) && isset($row['file'])) {
            $found[(string) $row['file']] = (array) ($row['faces'] ?? []);
        }
    }

    return $found;
}

/** A 64-bit difference hash, as 16 hex characters: near pictures differ in few bits. */
function demo_dhash(Imagick $image): string
{
    $small = clone $image;
    $small->transformImageColorspace(Imagick::COLORSPACE_GRAY);
    $small->resizeImage(9, 8, Imagick::FILTER_BOX, 1);
    $pixels = $small->exportImagePixels(0, 0, 9, 8, 'I', Imagick::PIXEL_CHAR);
    $bits = '';
    for ($y = 0; $y < 8; $y++) {
        for ($x = 0; $x < 8; $x++) {
            $bits .= $pixels[$y * 9 + $x] > $pixels[$y * 9 + $x + 1] ? '1' : '0';
        }
    }

    return str_pad(base_convert(substr($bits, 0, 32), 2, 16), 8, '0', STR_PAD_LEFT) . str_pad(base_convert(substr($bits, 32), 2, 16), 8, '0', STR_PAD_LEFT);
}

function demo_distance(string $a, string $b): int
{
    $d = 0;
    for ($i = 0; $i < 16; $i += 8) {
        $d += substr_count(decbin(hexdec(substr($a, $i, 8)) ^ hexdec(substr($b, $i, 8))), '1');
    }

    return $d;
}

/** A frame of one flat colour round a photograph: two opposite edges a few percent deep, flat. */
function demo_bordered(Imagick $image): bool
{
    $w = $image->getImageWidth();
    $h = $image->getImageHeight();
    $depth = max(4, (int) round(min($w, $h) * 0.02));
    $flat = static function (int $x, int $y, int $cw, int $ch) use ($image): bool {
        $strip = clone $image;
        $strip->cropImage($cw, $ch, $x, $y);
        $strip->transformImageColorspace(Imagick::COLORSPACE_GRAY);
        $stats = $strip->getImageChannelStatistics()[Imagick::CHANNEL_GRAY] ?? null;

        return $stats !== null && $stats['standardDeviation'] / $strip->getQuantumRange()['quantumRangeLong'] < 0.012;
    };

    return ($flat(0, 0, $w, $depth) && $flat(0, $h - $depth, $w, $depth)) || ($flat(0, 0, $depth, $h) && $flat($w - $depth, 0, $depth, $h));
}

/** Mean luminance 0..1 and colourfulness 0..1, from a small copy. */
function demo_light(Imagick $image): array
{
    $small = clone $image;
    $small->resizeImage(64, 64, Imagick::FILTER_BOX, 1);
    $rgb = $small->exportImagePixels(0, 0, 64, 64, 'RGB', Imagick::PIXEL_CHAR);
    $sum = 0.0;
    $chroma = 0.0;
    for ($i = 0; $i < count($rgb); $i += 3) {
        [$r, $g, $b] = [$rgb[$i] / 255, $rgb[$i + 1] / 255, $rgb[$i + 2] / 255];
        $sum += 0.2126 * $r + 0.7152 * $g + 0.0722 * $b;
        $chroma += max($r, $g, $b) - min($r, $g, $b);
    }
    $n = count($rgb) / 3;

    return ['luminance' => $sum / $n, 'colour' => $chroma / $n];
}
